;//Map header file for CHM project
;//Automatically generated by Easy CHM.
;//Website : http://www.zipghost.com
;//Email   : webmaster@zipghost.com
;//Date    : 2017-3-9 1:21:30

;//NOTE:
;//All strings after the ";" are commnets, they will be ignored by the CHM Compiler.

#define IDH_1085	1085	; Ocara手册 Ocara简介.html
#define IDH_1086	1086	; 关于API API大全\API介绍.html
#define IDH_1080	1080	; URL生成 函数智能\URL生成.html
#define IDH_1079	1079	; 内容处理 函数智能\内容处理.html
#define IDH_1081	1081	; 数组 函数智能\数组.html
#define IDH_1082	1082	; 文件目录 函数智能\文件目录.html
#define IDH_1083	1083	; 系统应用 函数智能\系统应用.html
#define IDH_1084	1084	; 智能转换 函数智能\转换.html
#define IDH_1071	1071	; MVC模型架构 基础知识和操作\MVC模型架构.html
#define IDH_1072	1072	; PHP命令执行 基础知识和操作\PHP命令执行.html
#define IDH_1073	1073	; URL路由 基础知识和操作\URL路由.htm
#define IDH_1074	1074	; 单入口多通道 基础知识和操作\单入口多通道.html
#define IDH_1078	1078	; 目录结构 基础知识和操作\目录结构.html
#define IDH_1075	1075	; 通道的使用 基础知识和操作\多通道的使用.html
#define IDH_1077	1077	; 系统模式 基础知识和操作\系统模式.html
#define IDH_1076	1076	; 新建应用 基础知识和操作\新建应用.html
#define IDH_1065	1065	; 开发者管理 开发者中心\开发者管理.html
#define IDH_1064	1064	; 开发者中心介绍 开发者中心\开发者中心介绍.html
#define IDH_1067	1067	; 添加动作（Action） 开发者中心\添加动作.html
#define IDH_1068	1068	; 添加控制器（Controller） 开发者中心\添加控制器.html
#define IDH_1069	1069	; 添加模块（Module） 开发者中心\添加模块.html
#define IDH_1070	1070	; 添加数据模型（Model） 开发者中心\添加数据模型.html
#define IDH_1066	1066	; 新建视图模板 开发者中心\新建视图模板.html
#define IDH_1056	1056	; Ajax处理 控制器层\Ajax处理.html
#define IDH_1058	1058	; Session处理 控制器层\Session处理.html
#define IDH_1052	1052	; 动作action的使用 控制器层\动作Action的使用.html
#define IDH_1054	1054	; 多语言功能 控制器层\多语言功能.html
#define IDH_1063	1063	; 分页的使用 控制器层\分页的使用.html
#define IDH_1053	1053	; 更改控制器执行流程 控制器层\更改控制器执行流程.html
#define IDH_1061	1061	; 缓存使用 控制器层\缓存使用.html
#define IDH_1057	1057	; 角色权限控制（OCAuth） 控制器层\角色权限控制.html
#define IDH_1051	1051	; 静态生成 控制器层\静态生成.html
#define IDH_1062	1062	; 控制器的使用 控制器层\控制器的使用.html
#define IDH_1055	1055	; 类的自动加载 控制器层\类的自动加载.html
#define IDH_1060	1060	; 模块的使用 控制器层\模块的使用.html
#define IDH_1059	1059	; 伪静态 控制器层\伪静态.html
#define IDH_1047	1047	; 系统配置 控制器层\系统配置.html
#define IDH_1048	1048	; 虚拟全局变量 控制器层\虚拟全局变量.html
#define IDH_1049	1049	; 异常错误处理 控制器层\异常错误处理.html
#define IDH_1050	1050	; 自定义回调 控制器层\自定义回调.html
#define IDH_1031	1031	; Excel生成 扩展插件\Excel生成.html
#define IDH_1032	1032	; FTP处理 扩展插件\FTP处理.html
#define IDH_1045	1045	; Socket处理 扩展插件\Socket处理.html
#define IDH_1033	1033	; XML处理 扩展插件\XML处理.html
#define IDH_1044	1044	; 分页 扩展插件\分页.html
#define IDH_1042	1042	; 静态生成 扩展插件\静态生成.html
#define IDH_1040	1040	; 权限设置 扩展插件\权限设置.html
#define IDH_1046	1046	; 日期时间 扩展插件\日期时间.html
#define IDH_1039	1039	; 日志处理 扩展插件\日志处理.html
#define IDH_1034	1034	; 图片处理 扩展插件\图片处理.html
#define IDH_1037	1037	; 文件处理 扩展插件\文件处理.html
#define IDH_1038	1038	; 文件缓存 扩展插件\文件缓存.html
#define IDH_1035	1035	; 文件上传 扩展插件\文件上传.html
#define IDH_1036	1036	; 文件下载 扩展插件\文件下载.html
#define IDH_1043	1043	; 验证码生成 扩展插件\验证码生成.html
#define IDH_1041	1041	; 邮件发送 扩展插件\邮件发送.html
#define IDH_1030	1030	; 实例下载 实例\实例下载.html
#define IDH_1028	1028	; 1.1-新建应用 实例\实例1-Hello World!\1.1-新建应用.html
#define IDH_1029	1029	; 1.2-新建首页 实例\实例1-Hello World!\1.2-新建首页.html
#define IDH_1024	1024	; 2.1-准备工作 实例\实例2-留言本\2.1-准备工作.html
#define IDH_1027	1027	; 2.2-添加留言 实例\实例2-留言本\2.2-添加留言.html
#define IDH_1026	1026	; 2.3-后台管理留言 实例\实例2-留言本\2.3-后台管理留言.html
#define IDH_1025	1025	; 2.4-留言删除 实例\实例2-留言本\2.4-留言删除.html
#define IDH_1015	1015	; 表单控件的生成 视图层\表单控件.html
#define IDH_1018	1018	; 表单令牌 视图层\表单令牌.html
#define IDH_1014	1014	; 表单生成 视图层\表单生成.html
#define IDH_1016	1016	; 表单验证 视图层\表单验证.html
#define IDH_1013	1013	; 跨页表单生成 视图层\跨页表单生成.html
#define IDH_1022	1022	; 模板的使用 视图层\模板的使用.html
#define IDH_1020	1020	; 模板区块 视图层\模板区块.html
#define IDH_1021	1021	; 模板引擎 视图层\模板引擎.html
#define IDH_1017	1017	; 模板引擎扩展 视图层\模板引擎扩展.html
#define IDH_1019	1019	; 模板助手 视图层\模板助手.html
#define IDH_1023	1023	; 页面布局 视图层\页面布局.html
#define IDH_1005	1005	; ORM模型 数据模型层\ORM模型的使用.html
#define IDH_1006	1006	; SQL安全过滤 数据模型层\SQL安全过滤.html
#define IDH_1007	1007	; SQL查询语句生成 数据模型层\SQL语句生成.html
#define IDH_1012	1012	; 查询缓存 数据模型层\查询缓存.html
#define IDH_1004	1004	; 分库分表 数据模型层\分库分表.html
#define IDH_1000	1000	; 使用原生的SQL语句 数据模型层\如何使用原生的sql语句.html
#define IDH_1002	1002	; 事务处理 数据模型层\事务处理.html
#define IDH_1010	1010	; 数据操作 数据模型层\数据操作.html
#define IDH_1011	1011	; 数据查询 数据模型层\数据查询.html
#define IDH_1008	1008	; 数据库的使用 数据模型层\数据库的使用.html
#define IDH_1003	1003	; 数据库配置 数据模型层\数据库设置.html
#define IDH_1001	1001	; 数据模型的使用 数据模型层\数据模型的使用.html
#define IDH_1009	1009	; 字段别名 数据模型层\字段别名.html
