;//Map header file for CHM project
;//Automatically generated by Easy CHM.
;//Website : http://www.zipghost.com
;//Email   : webmaster@zipghost.com
;//Date    : 2020/3/10 16:50:26

;//NOTE:
;//All strings after the ";" are commnets, they will be ignored by the CHM Compiler.

#define IDH_1102	1102	; Ocara简介 Ocara简介.html
#define IDH_1103	1103	; 开始使用 开始使用.html
#define IDH_1007	1007	; 1.1 MVC模型架构 1.基础概念和操作\1.1_MVC模型架构.html
#define IDH_1008	1008	; 1.2 控制反转和依赖注入 1.基础概念和操作\1.2_控制反转和依赖注入.html
#define IDH_1009	1009	; 1.3 领域驱动设计 1.基础概念和操作\1.3_领域驱动设计.html
#define IDH_1010	1010	; 1.4 类的自动加载 1.基础概念和操作\1.4_类的自动加载.html
#define IDH_1011	1011	; 1.5 系统模式 1.基础概念和操作\1.5_系统模式.html
#define IDH_1012	1012	; 1.6 目录结构 1.基础概念和操作\1.6_目录结构.html
#define IDH_1013	1013	; 1.7 事件回调 1.基础概念和操作\1.7_事件回调.html
#define IDH_1014	1014	; 1.8 动态行为绑定 1.基础概念和操作\1.8_动态行为绑定.html
#define IDH_1015	1015	; 1.9 URL格式 1.基础概念和操作\1.9_URL格式.htm
#define IDH_1000	1000	; 1.10 伪静态 1.基础概念和操作\1.10_伪静态.html
#define IDH_1001	1001	; 1.11 虚拟全局变量 1.基础概念和操作\1.11_虚拟全局变量.html
#define IDH_1002	1002	; 1.12 PHP命令执行 1.基础概念和操作\1.12_PHP命令执行.html
#define IDH_1003	1003	; 1.13 单入口多通道 1.基础概念和操作\1.13_单入口多通道.html
#define IDH_1004	1004	; 1.14 通道的使用 1.基础概念和操作\1.14_多通道的使用.html
#define IDH_1005	1005	; 1.15 新建应用 1.基础概念和操作\1.15_新建应用.html
#define IDH_1006	1006	; 1.16 插件委托机制 1.基础概念和操作\1.16_插件委托机制.html
#define IDH_1016	1016	; 2.1 开发者中心介绍 2.开发者中心\2.1_开发者中心介绍.html
#define IDH_1017	1017	; 2.2 添加模块（Module） 2.开发者中心\2.2_添加模块.html
#define IDH_1018	1018	; 2.3 添加控制器（Controller） 2.开发者中心\2.3_添加控制器.html
#define IDH_1019	1019	; 2.4 添加动作（Action） 2.开发者中心\2.4_添加动作.html
#define IDH_1020	1020	; 2.5 添加数据模型 2.开发者中心\2.5_添加数据模型.html
#define IDH_1021	1021	; 2.6 添加缓存模型（Model） 2.开发者中心\2.6_添加缓存模型.html
#define IDH_1022	1022	; 2.7 账号管理 2.开发者中心\2.7_账号管理.html
#define IDH_1023	1023	; 2.8 更新字段缓存 2.开发者中心\2.8_更新字段缓存.html
#define IDH_1024	1024	; 3.1 系统应用 3.函数智能\3.1_系统应用.html
#define IDH_1025	1025	; 3.2 智能转换 3.函数智能\3.2_转换.html
#define IDH_1026	1026	; 3.3 文件目录 3.函数智能\3.3_文件目录.html
#define IDH_1027	1027	; 3.4 数组 3.函数智能\3.4_数组.html
#define IDH_1028	1028	; 3.5 内容处理 3.函数智能\3.5_内容处理.html
#define IDH_1029	1029	; 3.6 URL生成 3.函数智能\3.6_URL生成.html
#define IDH_1040	1040	; 4.1 系统配置 4.控制器层\4.1_系统配置.html
#define IDH_1045	1045	; 4.2 缓存使用 4.控制器层\4.2_缓存使用.html
#define IDH_1046	1046	; 4.3 多语言功能 4.控制器层\4.3_多语言功能.html
#define IDH_1047	1047	; 4.4 依赖注入容器 4.控制器层\4.4_依赖注入容器.html
#define IDH_1048	1048	; 4.5 服务提供器 4.控制器层\4.5_服务提供器.html
#define IDH_1049	1049	; 4.6 资源提供器 4.控制器层\4.6_资源提供器.html
#define IDH_1050	1050	; 4.7 异常错误处理 4.控制器层\4.7_异常错误处理.html
#define IDH_1051	1051	; 4.8 控制器的使用 4.控制器层\4.8_控制器的使用.html
#define IDH_1052	1052	; 4.9 动作action的使用 4.控制器层\4.9_动作Action的使用.html
#define IDH_1030	1030	; 4.10 数据验证 4.控制器层\4.10_数据验证.html
#define IDH_1031	1031	; 4.11 HTTP请求 4.控制器层\4.11_HTTP请求.html
#define IDH_1032	1032	; 4.12 Ajax处理 4.控制器层\4.12_Ajax处理.html
#define IDH_1033	1033	; 4.13 HTTP响应 4.控制器层\4.13_HTTP响应.html
#define IDH_1034	1034	; 4.14 Api控制器模块 4.控制器层\4.14_Api控制器模块.html
#define IDH_1035	1035	; 4.15 Rest控制器模块 4.控制器层\4.15_Rest控制器模块.html
#define IDH_1036	1036	; 4.16 Session处理 4.控制器层\4.16_Session处理.html
#define IDH_1037	1037	; 4.17 Session操作 4.控制器层\4.17_Session操作.html
#define IDH_1038	1038	; 4.18 Cookie使用 4.控制器层\4.18_Cookie使用.html
#define IDH_1039	1039	; 4.19 分页的使用 4.控制器层\4.19_分页的使用.html
#define IDH_1041	1041	; 4.20 静态生成 4.控制器层\4.20_静态生成.html
#define IDH_1042	1042	; 4.21 角色权限控制 4.控制器层\4.21_角色权限控制.html
#define IDH_1043	1043	; 4.22 单元测试 4.控制器层\4.22_单元测试.html
#define IDH_1044	1044	; 4.23 单元测试编辑器设置分享 4.控制器层\4.23_单元测试编辑器设置分享.html
#define IDH_1060	1060	; 5.1 数据库配置 5.数据模型层\5.1_数据库配置.html
#define IDH_1061	1061	; 5.2 数据库的使用 5.数据模型层\5.2_数据库的使用.html
#define IDH_1062	1062	; 5.3 数据模型的使用 5.数据模型层\5.3_数据模型的使用.html
#define IDH_1063	1063	; 5.4 实体模型（ORM） 5.数据模型层\5.4_实体模型（ORM）.html
#define IDH_1064	1064	; 5.5 缓存模型 5.数据模型层\5.5_缓存模型.html
#define IDH_1065	1065	; 5.6 事务处理 5.数据模型层\5.6_事务处理.html
#define IDH_1066	1066	; 5.7 数据库查询 5.数据模型层\5.7_数据库查询.html
#define IDH_1067	1067	; 5.8 更多数据库查询函数 5.数据模型层\5.8_更多数据库查询函数.html
#define IDH_1068	1068	; 5.9 数据库操作 5.数据模型层\5.9_数据库操作.html
#define IDH_1053	1053	; 5.10 关联模型操作 5.数据模型层\5.10_关联模型操作.html
#define IDH_1054	1054	; 5.11 字段别名 5.数据模型层\5.11_字段别名.html
#define IDH_1055	1055	; 5.12 分库分表 5.数据模型层\5.12_分库分表.html
#define IDH_1056	1056	; 5.13 SQL安全防范 5.数据模型层\5.13_SQL安全防范.html
#define IDH_1057	1057	; 5.14 忽略SQL安全过滤 5.数据模型层\5.14_忽略SQL安全过滤.html
#define IDH_1058	1058	; 5.15 逻辑实体和枚举常量对象 5.数据模型层\5.15_逻辑实体和枚举常量对象.html
#define IDH_1059	1059	; 5.16 默认条件和字段 5.数据模型层\5.16_默认条件和字段.html
#define IDH_1069	1069	; 6.1 页面布局 6.视图层\6.1_页面布局.html
#define IDH_1070	1070	; 6.2 模板的使用 6.视图层\6.2_模板的使用.html
#define IDH_1071	1071	; 6.3 模板区块 6.视图层\6.3_模板区块.html
#define IDH_1072	1072	; 6.4 模板助手 6.视图层\6.4_模板助手.html
#define IDH_1073	1073	; 6.5 模板引擎 6.视图层\6.5_模板引擎.html
#define IDH_1074	1074	; 6.6 模板引擎扩展 6.视图层\6.6_模板引擎扩展.html
#define IDH_1075	1075	; 6.7 表单令牌 6.视图层\6.7_表单令牌.html
#define IDH_1076	1076	; 6.8 表单生成 6.视图层\6.8_表单生成.html
#define IDH_1077	1077	; 6.9 表单控件的生成 6.视图层\6.9_表单控件.html
#define IDH_1086	1086	; 7.1 Excel生成 7.扩展插件\7.1_Excel生成.html
#define IDH_1087	1087	; 7.2 XML处理 7.扩展插件\7.2_XML处理.html
#define IDH_1088	1088	; 7.3 分页 7.扩展插件\7.3_分页.html
#define IDH_1089	1089	; 7.4 文件上传 7.扩展插件\7.4_文件上传.html
#define IDH_1090	1090	; 7.5 文件下载 7.扩展插件\7.5_文件下载.html
#define IDH_1091	1091	; 7.6 文件处理 7.扩展插件\7.6_文件处理.html
#define IDH_1092	1092	; 7.7 文件日志处理 7.扩展插件\7.7_文件日志处理.html
#define IDH_1093	1093	; 7.8 文件缓存 7.扩展插件\7.8_文件缓存.html
#define IDH_1094	1094	; 7.9 日期时间 7.扩展插件\7.9_日期时间.html
#define IDH_1078	1078	; 7.10 图片处理 7.扩展插件\7.10_图片处理.html
#define IDH_1079	1079	; 7.11 随机码生成 7.扩展插件\7.11_随机码生成.html
#define IDH_1080	1080	; 7.12 验证码生成 7.扩展插件\7.12_验证码生成.html
#define IDH_1081	1081	; 7.13 邮件发送 7.扩展插件\7.13_邮件发送.html
#define IDH_1082	1082	; 7.14 Socket处理 7.扩展插件\7.14_Socket处理.html
#define IDH_1083	1083	; 7.15 FTP处理 7.扩展插件\7.15_FTP处理.html
#define IDH_1084	1084	; 7.16 权限设置 7.扩展插件\7.16_权限设置.html
#define IDH_1085	1085	; 7.17 静态生成 7.扩展插件\7.17_静态生成.html
#define IDH_1101	1101	; 实例下载 8.实例\实例下载.html
#define IDH_1095	1095	; 8.1.1 新建应用 8.实例\8.1 实例1-Hello World!\8.1.1_新建应用.html
#define IDH_1096	1096	; 8.1.2 新建首页 8.实例\8.1 实例1-Hello World!\8.1.2_新建首页.html
#define IDH_1097	1097	; 8.2.1 准备工作 8.实例\8.2 实例2-留言本\8.2.1_准备工作.html
#define IDH_1098	1098	; 8.2.2 添加留言 8.实例\8.2 实例2-留言本\8.2.2_添加留言.html
#define IDH_1099	1099	; 8.2.3 后台管理留言 8.实例\8.2 实例2-留言本\8.2.3_后台管理留言.html
#define IDH_1100	1100	; 8.2.4 删除留言 8.实例\8.2 实例2-留言本\8.2.4_删除留言.html
